### ISSUE TITLE
Dashboard widget order getting changed

### ISSUE THREAD

**Issue by long-wan-ep** [scribd/datadog_backup#146]
Due to the deepsort performed on the objects, the dashboard widgets could have the order changed when sorted, backed up, then restored to datadog. I was able to get around this by adding `array: false` to deepsort(ie. `JSON.pretty_generate(object.deep_sort(array: false))`). For situations where preserving the order of widgets is important, it may be worth adding a parameter for disabling array sorting.

**Comment by long-wan-ep** [comment]
Hi @jim80net, is this project still being maintained? I could help make a contribution for this, or if not I could just use `JSON.pretty_generate(object.deep_sort(array: false))` in my fork. Thanks.

**Comment by jim80net** [comment]
@long-wan-ep, thanks for raising the issue.  The project is still maintained and is actively being used at Scribd. 

A contribution would be very welcome.

**Comment by long-wan-ep** [comment]
Sounds good, created a PR: https://github.com/scribd/datadog_backup/pull/147.

**Comment by jim80net** [comment]
Thanks @long-wan-ep merged and released in [3.2.0!](https://github.com/scribd/datadog_backup/releases/tag/v3.2.0)
