### ISSUE TITLE
Error when restoring a dashboard that has been deleted in datadog

### ISSUE THREAD

**Issue by long-wan-ep** [scribd/datadog_backup#148]
Steps to reproduce:
1. Backup a dashboard
2. Delete the dashboard in Datadog
3. Restore the dashboard in interactive mode

Expected behavior:
1. Dashboard gets created in Datadog
2. ID updated for local backup

Actual behavior:
1. Errors with `the server responded with status 404 (Faraday::ResourceNotFound)` when the diff method is called.

This doesn't happen for monitors and synthetics, as they're already handling the 404; however after entering `r` in the interactive prompt to restore, it errors with `the server responded with status 404 (Faraday::ResourceNotFound)` in the `restore` method.

**Comment by long-wan-ep** [comment]
I can look into fixing this and create a PR.

**Comment by jim80net** [comment]
Thank you for finding and filing this bug. Your contribution would be very welcome!

**Comment by long-wan-ep** [comment]
Created a PR: https://github.com/scribd/datadog_backup/pull/150
