### ISSUE TITLE
Add SLOs to backup

### ISSUE THREAD

**Issue by lewhit** [scribd/datadog_backup#154]
We're starting to rely on Datadog's implementation of Service Level Objectives pretty heavily. We also use the backups we take of our monitors and dashboards to determine whether custom metrics are being used (or not). We'd like to be able to find out if metrics/tags are also being used in any SLOs. I have a branch to add this functionality, but opening up to conversation.

**Comment by jim80net** [comment]
Merged #155. Thanks again @lewhit =D
