### ISSUE TITLE
the server responded with status 429

### ISSUE THREAD

**Issue by jsotopian-chwy** [scribd/datadog_backup#161]
We can no longer pull a full backup of our DD configurations, we are getting "the server responded with status 429". 

We can pull monitors-only, but even pulling dashboards-only fails with the same rate-limiting error.

**Comment by kamranf** [comment]
Thanks for reporting this @jsotopian-chwy. Will look into it next week.

**Comment by kamranf** [comment]
This is now addressed per https://github.com/scribd/datadog_backup/pull/162 thanks to @maratkomarov 
Please update to the latest gem version to.

**Comment by jsotopian-chwy** [comment]
Good morning @kamranf,
Thanks for looking into this. I updated the gem, and now I am getting a different error.

`/var/lib/gems/3.0.0/gems/datadog_backup-4.0.1/lib/datadog_backup/resources.rb:21:in `<class:Resources>': uninitialized constant Faraday::TooManyRequestsError (NameError)
        from /var/lib/gems/3.0.0/gems/datadog_backup-4.0.1/lib/datadog_backup/resources.rb:11:in `<module:DatadogBackup>'
        from /var/lib/gems/3.0.0/gems/datadog_backup-4.0.1/lib/datadog_backup/resources.rb:8:in `<top (required)>'
        from /var/lib/gems/3.0.0/gems/datadog_backup-4.0.1/lib/datadog_backup.rb:8:in `require_relative'
        from /var/lib/gems/3.0.0/gems/datadog_backup-4.0.1/lib/datadog_backup.rb:8:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.0.0/gems/datadog_backup-4.0.1/bin/datadog_backup:12:in `<top (required)>'
        from /usr/local/bin/datadog_backup:25:in `load'
        from /usr/local/bin/datadog_backup:25:in `<main>'`

**Comment by kamranf** [comment]
@jsotopian-chwy I believe you just need to update `faraday` to 2.9.0 to resolve that. Let me know.

**Comment by jsotopian-chwy** [comment]
That did the trick, it is working now. Thanks for the support!

**Comment by jsotopian-chwy** [comment]
@kamranf That did the trick, it is working now. Thanks for the support!
