### ISSUE TITLE
add EU Account in datadog

### ISSUE THREAD

**Issue by lekesako** [scribd/datadog_backup#87]
Hi,

can you add EU Region for calling Datadog API ?
by default, it call datadoghq.com
can you add a parameter for region ? (eu, com, etc ) ?
and configuration datadog host in api call ? 

thanks

**Comment by jim80net** [comment]
Hi @lekesako, 

Looking into this, the dogapi gem will automatically pickup the `DATADOG_HOST` environment variable when you use this gem. I've gone ahead and added documentation that is released in v1.0.5, but this should work in earlier releases as well.
