### ISSUE TITLE
Issue to execute datadog_backup

### ISSUE THREAD

**Issue by lekesako** [scribd/datadog_backup#88]
Hi,

i have an error to execute datadog_backup. 

root@ip-10-167-110-36:~# datadog_backup backup
Traceback (most recent call last):
        6: from /usr/local/bin/datadog_backup:23:in `<main>'
        5: from /usr/local/bin/datadog_backup:23:in `load'
        4: from /root/.gem/ruby/2.5.0/gems/datadog_backup-1.0.5/bin/datadog_backup:9:in `<top (required)>'
        3: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        2: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        1: from /root/.gem/ruby/2.5.0/gems/datadog_backup-1.0.5/lib/datadog_backup.rb:7:in `<top (required)>'
/root/.gem/ruby/2.5.0/gems/datadog_backup-1.0.5/lib/datadog_backup.rb:7:in `require_relative': /root/.gem/ruby/2.5.0/gems/datadog_backup-1.0.5/lib/datadog_backup/local_filesystem.rb:49: syntax error, unexpected ']' (SyntaxError)
...e(filepath).strip.downcase[1..].to_sym

root@ip-10-167-110-36:~# ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

where i am wrong ? 

thanks

**Comment by jim80net** [comment]
You're not wrong at all! Turns out I wasn't compatible with ruby-2.5. 

I've released a new version that is: https://github.com/scribd/datadog_backup/releases/tag/v1.1.0

To install it, use

``` 
gem install datadog_backup -v 1.1.0
```

Thanks for the report!
